### ISSUE TITLE
test extract data don't pass

### ISSUE THREAD

**Issue by rsharifnasab** [kian79/practice_web_scrapping#1]
hey, i saw that you write this test:
```python
import unittest
import scraper
def test_extract_data():
    1 / 0
```
normally we write tests to pass, if we don't want to write test, just write one test something like `assert True`, is there any specific reason that you wrote a test to fail?

**Comment by kian79** [comment]
Hi
Thanks for your attention. I actually wrote this to test my test and see if it works properly :))) but I forgot to delete it. thanks for reminding me.
